version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - ALLOWED_BUCKET=my-audio-bucket
      - REDIS_HOST=redis

  worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis